# Generated by Django 5.0.3 on 2025-02-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employment_status', models.CharField(max_length=50)),
                ('monthly_income', models.FloatField()),
                ('existing_loans', models.IntegerField()),
                ('credit_score', models.FloatField()),
                ('loan_amount_requested', models.FloatField()),
                ('debt_to_income_ratio', models.FloatField()),
                ('loan_purpose', models.CharField(max_length=100)),
                ('repayment_history', models.CharField(max_length=50)),
                ('defaulted', models.BooleanField()),
            ],
        ),
    ]
