# Generated by Django 5.0.3 on 2025-03-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
