# Generated by Django 5.0.3 on 2025-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_chatmessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='debt_to_income_ratio',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='defaulted',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='existing_loans',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount_requested',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_purpose',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='repayment_history',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='sanketborhade33@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(default='Personal Loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
