# Generated by Django 5.0.3 on 2025-03-17 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_remove_loanapplication_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
